# Generated by Django 2.2.24 on 2023-12-20 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20231219_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='todo.Labels'),
        ),
    ]
