# Generated by Django 2.2.24 on 2023-12-20 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20231220_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='label',
        ),
        migrations.DeleteModel(
            name='Labels',
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
